#!/usr/bin/env bash
#Install DotNet 2.1 on Ubuntu 
#ProfitTrailer VPS Enhancements: https://github.com/RchGrav/pt-scripts

source /etc/os-release
if [[ $ID != ubuntu ]]; then
   echo "ERROR: This script is meant for an Ubuntu based host"
   exit
fi

wget -q https://packages.microsoft.com/config/$ID/$VERSION_ID/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install aspnetcore-runtime-2.1

#Optional
#echo "export DOTNET_CLI_TELEMETRY_OPTOUT" >> ~/.profile
