#!/usr/bin/env bash
#Install DotNet Ubuntu 18.04 LTS (Bionic)
#ProfitTrailer VPS Enhancements: https://github.com/RchGrav/pt-scripts

wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install aspnetcore-runtime-2.1

#Optional
#echo "export DOTNET_CLI_TELEMETRY_OPTOUT" >> ~/.profile
