#!/bin/bash
printf "\nRe-initializing ProfitTrailer Services...\n\n"
/etc/init.d/pt restart
/etc/init.d/ptf restart
/etc/init.d/ptt restart
printf "\nProfitTrailer Log...\n\n"
(tail -n $(tput lines) -f "/var/log/pt.log" & P=$!; sleep 10; kill -9 $P)
printf "\nPT-Feeder Log...\n\n"
(tail -n $(tput lines) -f "/var/log/ptf.log" & P=$!; sleep 10; kill -9 $P)
printf "\nPT-Tracker Log...\n\n"
(tail -n $(tput lines) -f "/var/log/ptt.log" & P=$!; sleep 10; kill -9 $P)
printf "\nDone.\n\n"
