#!/usr/bin/env bash

apt-get install libssl-dev -y
apt-get install make -y
apt-get install build-essential -y
apt-get install software-properties-common -y
apt-get install rsync -y
add-apt-repository ppa:webupd8team/java -y
apt update -y
apt install oracle-java8-installer -y
javac -version
apt install oracle-java8-set-default -y
sleep 5

add-apt-repository ppa:certbot/certbot -y
apt update -y && apt install letsencrypt -y

#
#
######----------------USER
adduser pt
usermod -aG sudo pt
#cd /etc/
#sed -i.bak "/%root ALL=(ALL:ALL) ALL/a \
#pt477 ALL=(ALL:ALL) ALL \ " /etc/sudoers
#chown -R pt477:pt477 /home/pt477/;
sleep 5

##################-----SWAP-----------##################################
cd
apt-get update -y
fallocate -l 3G /swapfile;
ls -lh /swapfile;
chmod 600 /swapfile;
ls -lh /swapfile;
mkswap /swapfile;
swapon /swapfile;
swapon --show;
free -h;
swapon --show;
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab;
sleep 5
##################-----STUFF-----------##################################
#apt-get install fish -y
#apt-get -qq update -y

#apt-get install apparmor apparmor-profiles -y

###################-------------------------------#############
#cd
#apt-get install htop -y
#apt-get install ufw  -y
#ufw default deny incoming
#ufw default allow outgoing


#ufw allow 4777
#ufw allow 477
#ufw allow http
#ufw allow https
#ufw enable
#

####################------SECURE--shared-memory---#########################
echo "tmpfs     /dev/shm     tmpfs     defaults,noexec,nosuid,size=8g      0     0" | sudo tee -a /etc/fstab;
mount -o remount /dev/shm

################-------BASH-COMPLETION----------###########################

one="# enable bash completion in interactive shells
#if ! shopt -oq posix; then
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#  fi
#fi"
two="enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi"
find . -type f -not -iwholename '*.git*' -name "/etc/bash.bashrc" -exec sed -i "s#$one#$two#g" {} \;

service ssh restart
login pt


